# Diagnose directional disagreement between the KNF rule model and LiDAR GBM.
#
# Requires `dev/gutcheck_validation_record.R`. The output identifies where one
# method agrees with the recorded field-stage call and the other does not, then
# summarizes LiDAR structural metrics and probability uncertainty. It is a
# diagnostic for field review and data QA, not a causal analysis or independent
# accuracy assessment.

.normalized_entropy <- function(probabilities) {
  probabilities <- base::as.matrix(probabilities)
  -base::rowSums(ifelse(probabilities > 0, probabilities * base::log(probabilities), 0)) /
    base::log(base::ncol(probabilities))
}

.probability_margin <- function(probabilities) {
  probabilities <- base::as.matrix(probabilities)
  base::apply(probabilities, 1L, function(x) {
    ordered <- base::sort(x, decreasing = TRUE)
    ordered[1L] - ordered[2L]
  })
}

.disagreement_case_type <- function(field_class, rule_class, lidar_class) {
  base::ifelse(
    rule_class == field_class & lidar_class == field_class,
    "Both correct",
    base::ifelse(
      lidar_class == field_class & rule_class != field_class,
      "LiDAR correct; rule wrong",
      base::ifelse(
        rule_class == field_class & lidar_class != field_class,
        "Rule correct; LiDAR wrong",
        base::ifelse(
          rule_class == lidar_class,
          "Both wrong; same call",
          "Both wrong; different calls"
        )
      )
    )
  )
}

.disagreement_summary <- function(data, grouping) {
  groups <- base::split(data, interaction(data[, grouping, drop = FALSE], drop = TRUE, lex.order = TRUE))
  base::do.call(base::rbind, base::lapply(groups, function(part) {
    key <- part[1L, grouping, drop = FALSE]
    base::cbind(
      key, n = base::nrow(part),
      mean_lidar_confidence = base::mean(part$lidar_confidence),
      median_lidar_confidence = stats::median(part$lidar_confidence),
      mean_entropy = base::mean(part$lidar_entropy),
      median_entropy = stats::median(part$lidar_entropy),
      mean_margin = base::mean(part$lidar_margin),
      median_margin = stats::median(part$lidar_margin),
      row.names = NULL
    )
  }))
}

#' Build a directional LiDAR-versus-rule disagreement audit
#'
#' @param source_dir Directory containing the gut-check files.
#' @param output_dir Directory for generated audit CSVs.
#' @param tier One of the review tiers generated by
#'   `build_knf_gutcheck_record()`.
#' @param metrics Structural metrics to summarize by disagreement type.
#' @return An invisible data frame of eligible point-level diagnostic records.
analyze_knf_gutcheck_disagreement <- function(
    source_dir = "outputs/models",
    output_dir = "outputs/gutcheck_disagreement",
    tier = base::c("all_eligible", "review_not_flagged", "desk_review_flagged"),
    metrics = base::c(
      "zmax", "n_strata_low_mid", "n_gt_6_1",
      "midstory_mean_degree", "understory_mean_betweenness"
    )
) {
  tier <- base::match.arg(tier)
  if (!base::exists("build_knf_gutcheck_record", mode = "function")) {
    base::stop("Source dev/gutcheck_validation_record.R before running this script.", call. = FALSE)
  }
  record <- build_knf_gutcheck_record(
    source_dir = source_dir,
    output_dir = base::file.path(output_dir, "comparison_record")
  )
  data <- record$points
  if (!base::all(metrics %in% base::names(data))) {
    base::stop("All requested metrics must be present in the joined gut-check layer.", call. = FALSE)
  }
  tier_rows <- base::switch(tier,
    all_eligible = data$eligible_three_class_comparison,
    review_not_flagged = data$eligible_three_class_comparison & data$review_status == "not_flagged",
    desk_review_flagged = data$eligible_three_class_comparison & data$review_status == "desk_review_flagged"
  )
  data <- data[tier_rows, , drop = FALSE]
  probabilities <- data[, base::c("msf", "se", "si"), drop = FALSE]
  data$lidar_confidence <- base::apply(probabilities, 1L, base::max)
  data$lidar_entropy <- .normalized_entropy(probabilities)
  data$lidar_margin <- .probability_margin(probabilities)
  data$case_type <- .disagreement_case_type(data$field_class, data$rule_class, data$lidar_class)
  data$prediction_direction <- base::ifelse(
    data$rule_class == data$lidar_class,
    "Models agree",
    base::paste0("Rule ", data$rule_class, " -> LiDAR ", data$lidar_class)
  )
  data$field_direction <- base::paste0("Field ", data$field_class, "; ", data$prediction_direction)

  if (!base::dir.exists(output_dir)) base::dir.create(output_dir, recursive = TRUE)
  by_case <- .disagreement_summary(data, "case_type")
  by_direction <- .disagreement_summary(data, base::c("field_class", "prediction_direction"))
  metric_summary <- base::do.call(base::rbind, base::lapply(metrics, function(metric) {
    groups <- base::split(data[[metric]], data$case_type)
    base::data.frame(
      metric = metric, case_type = base::names(groups), n = base::lengths(groups),
      mean = base::vapply(groups, base::mean, base::numeric(1)),
      median = base::vapply(groups, stats::median, base::numeric(1)),
      sd = base::vapply(groups, stats::sd, base::numeric(1)),
      stringsAsFactors = FALSE, row.names = NULL
    )
  }))
  utils::write.csv(data, base::file.path(output_dir, base::paste0(tier, "_point_audit.csv")), row.names = FALSE)
  utils::write.csv(by_case, base::file.path(output_dir, base::paste0(tier, "_case_summary.csv")), row.names = FALSE)
  utils::write.csv(by_direction, base::file.path(output_dir, base::paste0(tier, "_direction_summary.csv")), row.names = FALSE)
  utils::write.csv(metric_summary, base::file.path(output_dir, base::paste0(tier, "_metric_summary.csv")), row.names = FALSE)
  lines <- base::c(
    "# KNF rule-versus-LiDAR disagreement audit",
    "",
    "This diagnostic identifies the direction of rule-model and LiDAR-GBM disagreement at gut-check points. It must be interpreted against stand-derived field calls, review status, imagery, disturbance history, and map age; it is not pixel-level truth or causal evidence.",
    "",
    "## Case types",
    "",
    "- `Both correct`: both models agree with the three-class field call.",
    "- `LiDAR correct; rule wrong`: the priority set for understanding LiDAR-added structural evidence.",
    "- `Rule correct; LiDAR wrong`: the priority set for identifying LiDAR failure modes, label ambiguity, stale LiDAR, or missing predictors.",
    "- `Both wrong; same call`: likely shared limitation, crosswalk issue, label ambiguity, or a condition neither model represents well.",
    "- `Both wrong; different calls`: strongest disagreement / QA candidates.",
    "",
    "## Uncertainty fields",
    "",
    "- `lidar_confidence`: largest of P(MSF), P(SE), and P(SI).",
    "- `lidar_entropy`: normalized Shannon entropy of all three probabilities; values nearer one mean the probability distribution is more even and uncertain.",
    "- `lidar_margin`: highest probability minus second-highest probability; values nearer zero mean the top two classes are difficult to distinguish.",
    "",
    "## Outputs",
    "",
    "- `*_point_audit.csv`: field/rule/LiDAR classes, probabilities, uncertainty, review status, metrics, and directional case type.",
    "- `*_case_summary.csv`: counts and uncertainty summarized by case type.",
    "- `*_direction_summary.csv`: the same information by observed class and rule-to-LiDAR transition.",
    "- `*_metric_summary.csv`: structural-metric distributions by case type. These are descriptive, not causal effects."
  )
  base::writeLines(lines, base::file.path(output_dir, "README.md"))
  base::invisible(base::structure(
    data, tier = tier, metrics = metrics, class = c("gutcheck_disagreement", "data.frame")
  ))
}

#' Plot LiDAR uncertainty by rule-versus-LiDAR disagreement type
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_disagreement_uncertainty <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  long <- base::rbind(
    base::data.frame(case_type = audit$case_type, measure = "LiDAR confidence", value = audit$lidar_confidence),
    base::data.frame(case_type = audit$case_type, measure = "Normalized entropy", value = audit$lidar_entropy),
    base::data.frame(case_type = audit$case_type, measure = "Top-two probability margin", value = audit$lidar_margin)
  )
  ggplot2::ggplot(long, ggplot2::aes(x = case_type, y = value, fill = case_type)) +
    ggplot2::geom_boxplot(outlier.alpha = 0.3) +
    ggplot2::facet_wrap(~measure, scales = "free_y") +
    ggplot2::labs(
      title = "LiDAR uncertainty by comparison outcome",
      subtitle = "High entropy and low margin indicate an uncertain LiDAR call.",
      x = NULL, y = NULL, fill = NULL
    ) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 20, hjust = 1), legend.position = "none")
}

#' Plot structural metrics by rule-versus-LiDAR disagreement type
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_disagreement_metrics <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  long <- base::do.call(base::rbind, base::lapply(attr(audit, "metrics"), function(metric) {
    base::data.frame(case_type = audit$case_type, metric = metric, value = audit[[metric]])
  }))
  ggplot2::ggplot(long, ggplot2::aes(x = case_type, y = value, fill = case_type)) +
    ggplot2::geom_boxplot(outlier.alpha = 0.25) +
    ggplot2::facet_wrap(~metric, scales = "free_y") +
    ggplot2::labs(
      title = "LiDAR structural metrics by comparison outcome",
      subtitle = "Use alongside mapped context and comments to select sites for review.",
      x = NULL, y = "Observed 30 m LiDAR metric", fill = NULL
    ) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 20, hjust = 1), legend.position = "none")
}

#' Plot counts of each rule-versus-LiDAR comparison outcome
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_disagreement_counts <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  counts <- base::as.data.frame(base::table(audit$case_type), stringsAsFactors = FALSE)
  base::names(counts) <- base::c("case_type", "n")
  counts$case_type <- base::factor(counts$case_type, levels = counts$case_type[base::order(counts$n)])
  ggplot2::ggplot(counts, ggplot2::aes(x = case_type, y = n, fill = case_type)) +
    ggplot2::geom_col(show.legend = FALSE) +
    ggplot2::geom_text(ggplot2::aes(label = n), hjust = -0.15, size = 4) +
    ggplot2::coord_flip(clip = "off") +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.12))) +
    ggplot2::labs(
      title = "Where the KNF rule model and LiDAR GBM agree or disagree",
      subtitle = "Matched gut-check points with a three-class field call and both model predictions.",
      x = NULL, y = "Number of points"
    ) +
    ggplot2::theme_minimal(base_size = 13)
}

#' Plot field-call confusion matrices for the rule model and LiDAR GBM
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_comparison_confusion <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  classes <- base::c("msf", "se", "si")
  one_model <- function(prediction, model_name) {
    out <- base::as.data.frame(base::table(
      field_class = base::factor(audit$field_class, levels = classes),
      predicted_class = base::factor(audit[[prediction]], levels = classes)
    ), stringsAsFactors = FALSE)
    base::names(out)[3L] <- "n"
    out$model <- model_name
    out$row_total <- stats::ave(out$n, out$field_class, FUN = base::sum)
    out$percent_of_field_class <- ifelse(out$row_total > 0, out$n / out$row_total, NA_real_)
    out
  }
  data <- base::rbind(
    one_model("rule_class", "KNF rule model"),
    one_model("lidar_class", "LiDAR GBM")
  )
  ggplot2::ggplot(data, ggplot2::aes(x = predicted_class, y = field_class, fill = percent_of_field_class)) +
    ggplot2::geom_tile(color = "white", linewidth = 0.8) +
    ggplot2::geom_text(ggplot2::aes(label = base::paste0(n, "\n", base::sprintf("%.0f%%", 100 * percent_of_field_class))), size = 4) +
    ggplot2::facet_wrap(~model) +
    ggplot2::scale_fill_viridis_c(labels = scales::label_percent(accuracy = 1)) +
    ggplot2::labs(
      title = "Field-stage calls versus model predictions",
      subtitle = "Rows sum to 100% within each field-labeled class. Diagonal cells are agreement.",
      x = "Model prediction", y = "Recorded field stage", fill = "Within-field class"
    ) +
    ggplot2::theme_minimal(base_size = 13)
}

#' Plot rule-to-LiDAR transition counts within field classes
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_prediction_transitions <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  data <- audit[audit$prediction_direction != "Models agree", , drop = FALSE]
  counts <- base::as.data.frame(base::table(data$field_class, data$prediction_direction), stringsAsFactors = FALSE)
  base::names(counts) <- base::c("field_class", "prediction_direction", "n")
  counts <- counts[counts$n > 0L, , drop = FALSE]
  ggplot2::ggplot(counts, ggplot2::aes(x = stats::reorder(prediction_direction, n), y = n, fill = prediction_direction)) +
    ggplot2::geom_col(show.legend = FALSE) +
    ggplot2::geom_text(ggplot2::aes(label = n), hjust = -0.15, size = 3.5) +
    ggplot2::coord_flip(clip = "off") +
    ggplot2::facet_wrap(~field_class, scales = "free_y") +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.12))) +
    ggplot2::labs(
      title = "Direction of rule-versus-LiDAR disagreement",
      subtitle = "Only points where the two models give different structural-stage calls.",
      x = NULL, y = "Number of points"
    ) +
    ggplot2::theme_minimal(base_size = 12)
}

#' Plot agreement and disagreement outcomes within each field class
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_outcome_by_field_class <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  classes <- base::c("msf", "se", "si")
  outcomes <- base::c(
    "Both correct", "LiDAR correct; rule wrong", "Rule correct; LiDAR wrong",
    "Both wrong; same call", "Both wrong; different calls"
  )
  data <- base::as.data.frame(base::table(
    field_class = base::factor(audit$field_class, levels = classes),
    case_type = base::factor(audit$case_type, levels = outcomes)
  ), stringsAsFactors = FALSE)
  base::names(data)[3L] <- "n"
  data$total <- stats::ave(data$n, data$field_class, FUN = base::sum)
  data$proportion <- data$n / data$total
  ggplot2::ggplot(data, ggplot2::aes(x = case_type, y = field_class, fill = proportion)) +
    ggplot2::geom_tile(color = "white", linewidth = 0.8) +
    ggplot2::geom_text(ggplot2::aes(label = base::paste0(n, "\n", base::sprintf("%.0f%%", 100 * proportion))), size = 3.6) +
    ggplot2::scale_fill_viridis_c(labels = scales::label_percent(accuracy = 1)) +
    ggplot2::labs(
      title = "Agreement and disagreement within each recorded field class",
      subtitle = "Rows sum to 100%. This shows where each product's successes and errors occur.",
      x = NULL, y = "Recorded field stage", fill = "Within-field class"
    ) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 25, hjust = 1))
}

#' Plot structural and uncertainty profiles of agreement/disagreement outcomes
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @return A ggplot object.
plot_gutcheck_outcome_profiles <- function(audit) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  variables <- base::c(attr(audit, "metrics"), "lidar_entropy", "lidar_margin")
  labels <- base::c(
    zmax = "Maximum height", n_strata_low_mid = "Low-mid layering",
    n_gt_6_1 = "Vegetation > 6.1 m", midstory_mean_degree = "Midstory connectivity",
    understory_mean_betweenness = "Understory betweenness",
    lidar_entropy = "LiDAR uncertainty (entropy)", lidar_margin = "LiDAR separation (margin)"
  )
  outcomes <- base::c(
    "Both correct", "LiDAR correct; rule wrong", "Rule correct; LiDAR wrong",
    "Both wrong; same call", "Both wrong; different calls"
  )
  rows <- base::do.call(base::rbind, base::lapply(variables, function(variable) {
    overall_median <- stats::median(audit[[variable]], na.rm = TRUE)
    overall_sd <- stats::sd(audit[[variable]], na.rm = TRUE)
    groups <- base::split(audit[[variable]], audit$case_type)
    base::data.frame(
      variable = variable, case_type = base::names(groups),
      standardized_median_difference = base::vapply(groups, function(values) {
        (stats::median(values, na.rm = TRUE) - overall_median) / overall_sd
      }, base::numeric(1)),
      stringsAsFactors = FALSE, row.names = NULL
    )
  }))
  rows$case_type <- base::factor(rows$case_type, levels = outcomes)
  rows$variable <- base::factor(rows$variable, levels = variables, labels = labels[variables])
  ggplot2::ggplot(rows, ggplot2::aes(x = case_type, y = variable, fill = standardized_median_difference)) +
    ggplot2::geom_tile(color = "white", linewidth = 0.8) +
    ggplot2::geom_text(ggplot2::aes(label = base::sprintf("%+.1f", standardized_median_difference)), size = 3.8) +
    ggplot2::scale_fill_gradient2(low = "#2C7BB6", mid = "white", high = "#D7191C", midpoint = 0,
      name = "Median relative\nto all points\n(SD units)") +
    ggplot2::labs(
      title = "What distinguishes agreement and disagreement groups?",
      subtitle = "Values show each group's median relative to the full holdout set. They describe patterns, not causal effects.",
      x = NULL, y = NULL
    ) +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 25, hjust = 1))
}

#' Save presentation-ready gut-check disagreement figures
#'
#' @param audit Output from `analyze_knf_gutcheck_disagreement()`.
#' @param output_dir Directory for PNG figures.
#' @param prefix File-name prefix.
#' @param dpi Resolution for PNG figures. Use 600 for clear zooming and print.
#' @return An invisible named vector of figure paths.
save_gutcheck_disagreement_figures <- function(
    audit,
    output_dir = "outputs/gutcheck_disagreement/figures",
    prefix = "all_eligible",
    dpi = 600
) {
  if (!inherits(audit, "gutcheck_disagreement")) {
    base::stop("audit must come from analyze_knf_gutcheck_disagreement().", call. = FALSE)
  }
  if (!base::dir.exists(output_dir)) base::dir.create(output_dir, recursive = TRUE)
  plots <- base::list(
    comparison_outcomes = plot_gutcheck_disagreement_counts(audit),
    comparison_confusion = plot_gutcheck_comparison_confusion(audit),
    prediction_transitions = plot_gutcheck_prediction_transitions(audit),
    outcome_by_field_class = plot_gutcheck_outcome_by_field_class(audit),
    outcome_profiles = plot_gutcheck_outcome_profiles(audit),
    lidar_uncertainty = plot_gutcheck_disagreement_uncertainty(audit),
    structural_metrics = plot_gutcheck_disagreement_metrics(audit)
  )
  dimensions <- base::list(
    comparison_outcomes = base::c(11, 7), comparison_confusion = base::c(12, 7),
    prediction_transitions = base::c(13, 8), lidar_uncertainty = base::c(13, 8),
    structural_metrics = base::c(14, 9), outcome_by_field_class = base::c(13, 7),
    outcome_profiles = base::c(14, 8)
  )
  if (!base::is.numeric(dpi) || base::length(dpi) != 1L || !base::is.finite(dpi) || dpi < 72) {
    base::stop("dpi must be one finite numeric value of at least 72.", call. = FALSE)
  }
  png_paths <- base::vapply(base::names(plots), function(name) {
    path <- base::file.path(output_dir, base::paste0(prefix, "_", name, ".png"))
    ggplot2::ggsave(
      filename = path, plot = plots[[name]], width = dimensions[[name]][1L],
      height = dimensions[[name]][2L], units = "in", dpi = dpi, bg = "white"
    )
    path
  }, base::character(1))
  svg_paths <- base::vapply(base::names(plots), function(name) {
    path <- base::file.path(output_dir, base::paste0(prefix, "_", name, ".svg"))
    result <- base::try(ggplot2::ggsave(
      filename = path, plot = plots[[name]], width = dimensions[[name]][1L],
      height = dimensions[[name]][2L], units = "in", bg = "white"
    ), silent = TRUE)
    if (inherits(result, "try-error")) NA_character_ else path
  }, base::character(1))
  base::invisible(base::list(png = png_paths, svg = svg_paths))
}

# Example:
# source("dev/gutcheck_validation_record.R")
# source("dev/gutcheck_disagreement_analysis.R")
# audit <- analyze_knf_gutcheck_disagreement()
# plot_gutcheck_disagreement_uncertainty(audit)
# plot_gutcheck_disagreement_metrics(audit)
# save_gutcheck_disagreement_figures(audit)
